"""Prism CLI — a passthrough-first launcher for Claude Code.

`prism <anything>` forwards verbatim to `claude`, after ensuring a routing proxy is up.
Only three bare words are reserved for Prism itself: `setup`, `status`, `doctor`.
Use `prism -- <args>` to force a collision word through to claude.
"""
from __future__ import annotations

import os
import secrets
import signal
import subprocess
import sys

from . import config as cfgmod
from . import proxy as proxymod

RESERVED_VERBS = {"setup", "status", "doctor"}
INFORMATIONAL = {"--help", "-h", "--version", "-v"}
# Real `claude` subcommands that issue no model completion → don't gate on API keys.
NO_COMPLETION_SUBCOMMANDS = {
    "mcp", "doctor", "update", "auth", "plugin", "project",
    "install", "setup-token", "agents", "gateway", "auto-mode",
}
EXIT_PRISM_ERROR = 2  # Prism's own failures; claude's exit code is propagated otherwise.


class PrismError(Exception):
    pass


def partition_args(argv: list[str]) -> tuple[str, str | None, list[str]]:
    """Return (mode, verb, forward_args).

    mode ∈ {"mgmt", "passthrough", "passthrough_no_proxy"}.
    """
    if not argv:
        return ("passthrough", None, [])
    if argv[0] == "--":
        return ("passthrough", None, argv[1:])
    if argv[0] in RESERVED_VERBS:
        return ("mgmt", argv[0], argv[1:])
    if argv and all(a in INFORMATIONAL for a in argv):
        return ("passthrough_no_proxy", None, argv)
    return ("passthrough", None, argv)


def requires_completion(forward_args: list[str]) -> bool:
    """Whether this claude invocation will actually route a model completion."""
    if not forward_args:
        return True  # bare `prism` → interactive session
    if forward_args[0] in NO_COMPLETION_SUBCOMMANDS:
        return False
    if all(a in INFORMATIONAL for a in forward_args):
        return False
    return True


def build_claude_env(base_env: dict, base_url: str, token: str, cfg: dict) -> dict:
    env = dict(base_env)
    env["ANTHROPIC_BASE_URL"] = base_url
    env["ANTHROPIC_AUTH_TOKEN"] = token
    env.update(cfgmod.mapping_env(cfg))
    return env


# ── management verbs ─────────────────────────────────────────────────────────────

def _ensure_home() -> None:
    home = cfgmod.prism_home()
    home.mkdir(parents=True, exist_ok=True)
    os.chmod(home, 0o700)


def _ensure_master_key() -> str:
    p = cfgmod.master_key_path()
    if p.exists():
        return p.read_text().strip()
    key = "sk-prism-" + secrets.token_hex(24)
    fd = os.open(p, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(key)
    return key


def _write_hook_shim() -> None:
    """Co-located shim litellm loads by file path; fails LOUD if prism isn't importable."""
    cfgmod.hook_shim_path().write_text(
        "# Generated by Prism. Loaded by litellm via config `callbacks: prism_hook.instance`.\n"
        "try:\n"
        "    from prism.routing import instance\n"
        "except Exception as e:\n"
        "    import sys\n"
        "    print(f'prism.hook.import_failed: {e}', file=sys.stderr, flush=True)\n"
        "    raise\n"
    )
    os.chmod(cfgmod.hook_shim_path(), 0o600)


def _provision() -> None:
    """Idempotently create ~/.prism (config, master key, hook shim). Safe to re-run."""
    _ensure_home()
    cfg_p = cfgmod.config_path()
    if not cfg_p.exists():
        cfg_p.write_text(cfgmod._default_config_text())
    os.chmod(cfg_p, 0o600)
    _ensure_master_key()
    _write_hook_shim()


def cmd_setup(_args: list[str]) -> int:
    _provision()
    cfg = cfgmod.load_config()
    cfgmod.validate(cfg)
    keys = cfgmod.active_key_envs(cfg)
    print(f"Prism is set up at {cfgmod.prism_home()}")
    print(f"  config: {cfgmod.config_path()}")
    missing = [k for k in keys if not os.environ.get(k)]
    if missing:
        print("\nNext step — export your provider key(s):")
        for k in missing:
            print(f"  export {k}=...")
    print("\nThen just run:  prism            (or: prism -p 'hello')")
    return 0


def cmd_doctor(_args: list[str]) -> int:
    ok = True
    try:
        v = proxymod.assert_version_ok()
        print(f"✓ litellm {v} (>= 1.83.0)")
    except proxymod.ProxyError as e:
        ok = False
        print(f"✗ litellm: {e}")
    try:
        cfg = cfgmod.load_config()
        cfgmod.validate(cfg)
        print(f"✓ config valid: {cfgmod.config_path()}")
        for k in cfgmod.active_key_envs(cfg):
            mark = "✓" if os.environ.get(k) else "✗"
            print(f"  {mark} {k} {'set' if os.environ.get(k) else 'NOT set'}")
            ok = ok and bool(os.environ.get(k))
    except cfgmod.ConfigError as e:
        ok = False
        print(f"✗ config: {e}")
    claude = _find_claude()
    print(f"{'✓' if claude else '✗'} claude on PATH: {claude or 'NOT FOUND'}")
    return 0 if ok and claude else 1


def cmd_status(_args: list[str]) -> int:
    home = cfgmod.prism_home()
    print(f"Prism home: {home}  (exists={home.exists()})")
    if cfgmod.config_path().exists():
        try:
            cfg = cfgmod.load_config()
            print(f"config_hash: {cfgmod.config_hash(cfg)}")
            for role in cfgmod.REQUIRED_ROLES:
                print(f"  {role:11s} -> {cfgmod._route_model_string(cfg, role)}")
        except cfgmod.ConfigError as e:
            print(f"config error: {e}")
    else:
        print("no config yet — run `prism setup`.")
    return 0


# ── passthrough (the main path) ───────────────────────────────────────────────────

def _find_claude() -> str | None:
    from shutil import which

    return which("claude")


def _exec_claude(forward_args: list[str], env: dict | None = None) -> int:
    claude = _find_claude()
    if not claude:
        raise PrismError("`claude` not found on PATH — install Claude Code first.")
    proc = subprocess.Popen([claude, *forward_args], env=env)
    prev = signal.getsignal(signal.SIGINT)
    # A no-op handler (not SIG_IGN) so the parent survives Ctrl-C while claude — which
    # resets handlers to default on exec — receives SIGINT normally from the terminal.
    signal.signal(signal.SIGINT, lambda *_: None)
    try:
        while True:
            try:
                return proc.wait()
            except KeyboardInterrupt:
                continue
    finally:
        signal.signal(signal.SIGINT, prev)


def _warn_env_override(base_env: dict) -> None:
    for var in ("ANTHROPIC_BASE_URL", "ANTHROPIC_AUTH_TOKEN"):
        val = base_env.get(var)
        if val and "PRISM" not in val:
            print(
                f"prism: overriding your existing {var} to route through the local proxy "
                "(set PRISM_BYPASS=1 to run claude untouched).",
                file=sys.stderr,
            )
            return


def run_passthrough(forward_args: list[str]) -> int:
    if os.environ.get("PRISM_BYPASS") == "1":
        return _exec_claude(forward_args)

    _provision()  # idempotent: first run works without an explicit `prism setup`
    cfg = cfgmod.load_config()
    cfgmod.validate(cfg)

    if requires_completion(forward_args):
        missing = [k for k in cfgmod.active_key_envs(cfg) if not os.environ.get(k)]
        if missing:
            raise PrismError(
                f"{', '.join(missing)} not set — export your provider key(s), e.g. "
                f"`export {missing[0]}=...` (see `prism setup`)."
            )

    _warn_env_override(dict(os.environ))
    master_key = _ensure_master_key()
    proxy = proxymod.start(cfg, master_key)
    try:
        env = build_claude_env(dict(os.environ), proxy.base_url, master_key, cfg)
        return _exec_claude(forward_args, env)
    finally:
        proxy.stop()


# ── entrypoint ────────────────────────────────────────────────────────────────────

_MGMT = {"setup": cmd_setup, "status": cmd_status, "doctor": cmd_doctor}


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    try:
        mode, verb, forward = partition_args(argv)
        if mode == "mgmt":
            print(
                f"prism: running `{verb}` (Prism management). "
                f"To send \"{verb}\" to claude instead: prism -- {verb}",
                file=sys.stderr,
            )
            return _MGMT[verb](forward)  # type: ignore[index]
        if mode == "passthrough_no_proxy":
            return _exec_claude(forward)
        return run_passthrough(forward)
    except (PrismError, cfgmod.ConfigError, proxymod.ProxyError) as e:
        print(f"prism: {e}", file=sys.stderr)
        return EXIT_PRISM_ERROR


if __name__ == "__main__":
    raise SystemExit(main())
